version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - "jupyter-book config sphinx docs/"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - sphinx

conda:
  environment: conda_environment.yml

sphinx:
  builder: html
  fail_on_warning: true
