[build-system]
requires = ["setuptools>=64.0", "setuptools-scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "gprof_nn"
description = "The GPROF-NN satellite precipitation retrieval."
readme = "README.md"
requires-python = ">=3.7"
authors = [
    {name = "Simon Pfreundschuh", email = "simon.pfreundschuh@colostate.edu"}
]
dependencies = [
    "appdirs",
    "cartopy",
    "hdf5plugin",
    "filelock",
    "matplotlib",
    "numpy",
    "pytorch_retrieve>=0.1.6",
    "xarray[io]",
    "huggingface-hub",
    "ipywidgets",
    "hf_xet"
]
dynamic = ["version"]

[project.optional-dependencies]
docs = ["jupyter-book", "sphinx"]

[project.urls]
Homepage = "https://gprof_nn.readthedocs.io"

[project.scripts]
gprof_nn = "gprof_nn.cli:gprof_nn"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"gprof_nn" = ["config_files/*.toml", "sensors/*.toml", "files/*.nc", "files/*.rc"]

[tool.setuptools_scm]
fallback_version = "0+unknown"
