[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gprof_nn"
version = "0.8.1"
description = "The GPROF-NN satellite precipitation retrieval."
readme = "README.md"
requires-python = ">=3.7"
authors = [
    {name = "Simon Pfreundschuh", email = "simon.pfreundschuh@colostate.edu"}
]
dependencies = [
    "appdirs",
    "cartopy",
    "hdf5plugin",
    "filelock",
    "matplotlib",
    "numpy",
    "pytorch_retrieve>=0.1.2",
    "xarray[io]",
    "huggingface-hub",
    "ipywidgets"
]

[project.optional-dependencies]
docs = ["jupyter-book", "sphinx"]

[project.urls]
Homepage = "https://gprof_nn.readthedocs.io"

[project.scripts]
gprof_nn = "gprof_nn.cli:gprof_nn"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"gprof_nn" = ["config_files/*.toml", "sensors/*.toml", "files/*.nc", "files/*.rc"]
