[platform]
name = "wsfm1"
l1c_file_path = "/edata1/archive/GPM/1C_WSFM1_ITE"
l1c_file_prefix = "1C.WSFM1.MWI*"

[viewing_geometry]
kind = "Conical"
altitude = 854e3
scan_range = 140.0
pixels_per_scan = 400
earth_incidence_angle = 52.069
scan_offset = 15e3

[sensor]
kind = "ConstellationScanner"
frequencies = [10.65, 10.65, 18.7, 18.7, 23.8, 36.75, 36.75, 89.0, 89.0]
offsets = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
polarization = ["V", "H", "V", "H", "V", "V", "H", "V", "H"]
orographic_enhancement = [1.14100, 1.71287, 1.46721, 1.71271, 2.96671]
sim_file_pattern = "*.sim"
beam_width = [1.06, 1.06, 0.66, 0.66, 0.58, 0.43, 0.43, 0.43, 0.43, 0.43]
earth_incidence_angle = [52.069, 52.069, 52.069, 52.069, 52.069, 52.069, 52.069, 52.069, 52.069]
channel_drop = 0.1
scanline_drop = 0.1
pansat_products = ["l1c_xcal2026v_wsfm1_mwi_parv817"]

[sensor.gprof_channels]
0 = [0, 0]
1 = [0, 1]
2 = [1, 0]
3 = [1, 1]
4 = [2, 0]
6 = [3, 0]
7 = [3, 1]
8 = [5, 0]
9 = [5, 1]
