[platform]
name = "F15"
l1c_file_path = "/edata1/archive/GPM/1C_F15_V7"
l1c_file_prefix = "1C.F1?.SSMI"

[viewing_geometry]
kind = "Conical"
altitude = 853e3
earth_incidence_angle = 53.1
scan_range = 102.0
pixels_per_scan = 128
scan_offset = 12.5e3

[sensor]
kind = "ConstellationScanner"
frequencies = [19.35, 19.35, 22.235, 37.0, 37.0, 85.5, 85.5]
offsets = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
polarization = ["V", "H", "V", "V", "H", "V", "H"]
orographic_enhancement = [1.12398,1.69201,1.45721,1.68737,2.77979]
earth_incidence_angle = [53.1, 53.1, 53.1, 53.1, 53.1, 53.1, 53.1]
beam_width = [1.87, 1.87, 1.65, 1.1, 1.1, 0.43, 0.45]
channel_drop = 0.2
scanline_drop = 0.1
pansat_products = ["l1c_xcal2018v_f15_ssmi_v07"]

[sensor.gprof_channels]
2 = [0, 0]
3 = [0, 1]
4 = [0, 2]
6 = [0, 3]
7 = [0, 4]
8 = [1, 0]
9 = [1, 1]
