[stage_1]
dataset_module = "gprof_nn.data.training_data"
training_dataset = "GPROFNN1DDataset"
training_dataset_args = {{path="{training_data_path}"}}
validation_dataset_args = {{path="{validation_data_path}"}}
n_epochs = 20
batch_size = 0
optimizer = "AdamW"
optimizer_args = {{lr = 5e-4}}
scheduler = "CosineAnnealingLR"
scheduler_args = {{T_max = 20}}
metrics = ["CorrelationCoef", "MSE", "Bias"]
precision = "bfloat16"

[stage_2]
dataset_module = "gprof_nn.data.training_data"
training_dataset = "GPROFNN1DDataset"
training_dataset_args = {{path="{training_data_path}"}}
validation_dataset_args = {{path="{validation_data_path}"}}
n_epochs = 20
batch_size = 0
optimizer = "AdamW"
optimizer_args = {{lr = 5e-4}}
scheduler = "CosineAnnealingLR"
scheduler_args = {{T_max = 20}}
metrics = ["CorrelationCoef", "MSE", "Bias"]
reuse_optimizer = true
precision = "bfloat16"

[stage_3]
dataset_module = "gprof_nn.data.training_data"
training_dataset = "GPROFNN1DDataset"
training_dataset_args = {{path="{training_data_path}"}}
validation_dataset_args = {{path="{validation_data_path}"}}
n_epochs = 20
batch_size = 0
optimizer = "AdamW"
optimizer_args = {{lr = 5e-4}}
scheduler = "CosineAnnealingLR"
scheduler_args = {{T_max = 20}}
metrics = ["CorrelationCoef", "MSE", "Bias"]
reuse_optimizer = true
precision = "bfloat16"
